// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2z3vxxjXgxTS51MOdWryqG4zCettMfEE',
    appId: '1:771551034702:web:4d876ddc9a94869e18721f',
    messagingSenderId: '771551034702',
    projectId: 'fir-20312146-61f45',
    authDomain: 'fir-20312146-61f45.firebaseapp.com',
    storageBucket: 'fir-20312146-61f45.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOCsCz4kxIJYy85kiUHUIiOyWQyVsBDqI',
    appId: '1:771551034702:android:f2351dc13147156d18721f',
    messagingSenderId: '771551034702',
    projectId: 'fir-20312146-61f45',
    storageBucket: 'fir-20312146-61f45.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJXgFzQekO1R27FRElT9xXF9h7m3aziqw',
    appId: '1:771551034702:ios:f5026f627fdae2f518721f',
    messagingSenderId: '771551034702',
    projectId: 'fir-20312146-61f45',
    storageBucket: 'fir-20312146-61f45.appspot.com',
    iosClientId: '771551034702-l38kh237mkmpq773ahh7crnr01845dpn.apps.googleusercontent.com',
    iosBundleId: 'com.ifgabsp.projectGet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJXgFzQekO1R27FRElT9xXF9h7m3aziqw',
    appId: '1:771551034702:ios:f5026f627fdae2f518721f',
    messagingSenderId: '771551034702',
    projectId: 'fir-20312146-61f45',
    storageBucket: 'fir-20312146-61f45.appspot.com',
    iosClientId: '771551034702-l38kh237mkmpq773ahh7crnr01845dpn.apps.googleusercontent.com',
    iosBundleId: 'com.ifgabsp.projectGet',
  );
}
